kind: ConfigMap
metadata:
  name: vault-config
apiVersion: v1
data:
  vault.hcl: |-
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = "true"
    }

    storage "raft" {
      path    = "/vault/data"
      node_id = "node1"
    }

    api_addr = "http://0.0.0.0:8200"
    cluster_addr = "https://0.0.0.0:8201"
    ui = true
    disable_mlock=true
