apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: vault
    spec:
      containers:
        - command:
            - vault
            - server
            - -config=/vault.hcl
          image: hashicorp/vault
          name: vault
          ports:
            - containerPort: 8200
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          volumeMounts:
            - mountPath: /vault/data
              name: vault-data
            - mountPath: /vault/file
              name: vault-file
            - mountPath: /vault.hcl
              name: vault-config
              subPath: vault.hcl
      volumes:
        - configMap:
            items:
              - key: vault.hcl
                path: vault.hcl
            name: vault-config
          name: vault-config
        - hostPath:
            path: /disk1/vault/data
            type: DirectoryOrCreate
          name: vault-data
        - hostPath:
            path: /disk1/vault/file
            type: DirectoryOrCreate
          name: vault-file
---
